# Generated by Django 5.0.1 on 2024-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
